# Generated by Django 4.1.8 on 2023-04-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_news',
            field=models.BooleanField(default=False),
        ),
    ]
