# Generated by Django 4.1.8 on 2023-04-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_post_is_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_news',
            field=models.BooleanField(default=False),
        ),
    ]
