# Generated by Django 4.1.8 on 2023-04-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_post_is_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_news',
        ),
    ]
