# Generated by Django 4.2 on 2023-04-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_postcategory_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='author',
        ),
    ]
