# Generated by Django 4.2 on 2023-04-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_postcategory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_news',
            field=models.BooleanField(default=False),
        ),
    ]
