# Generated by Django 4.2 on 2023-04-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_rename_subscription_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_news',
        ),
    ]
